Create Shell Script Task
kossiitkgp/KOSS-Selection-Tasks pull request #22
Opened 2023-04-07 10:54 UTC by leader282

This task needs the freshers to create a shell script using bash terminal that generates a report from a CSV file. All relevant resource links have been added and also demo CSV and its output are present. This will be a teaching task and so they have to make a ppt showing how they made the script, the commands used and the output.

2023-05-03 20:05 UTC, leader282 commented
Added the blockchain task too in this. Here the freshers need to create a ppt regarding public-private key encryption, digital signatures, wallets, etc.

2023-05-05 17:06 UTC, harshkhandeparkar commented on Teaching/Blockchain/crypto.md
Suggestion: Add a hands-on demonstration task.

2023-05-06 09:36 UTC, Yureien requested changes

2023-05-06 09:36 UTC, Yureien commented on Teaching/Blockchain/crypto.md
> +This book can be used as a great reference : [Mastering Bitcoin](https://github.com/bitcoinbook/bitcoinbook/)
Add this reference: https://rosenbaum.se/book/grokking-bitcoin.html

2023-05-06 09:36 UTC, Yureien commented on Teaching/Blockchain/crypto.md
> +- Best practices for securing Bitcoin wallets, including the importance of backing up private keys and using multi-factor authentication.
Add another point:

- [Optional, but recommended] Use the `bitcoin-cli` client to make a regtest wallet, and try creating transactions.

2023-05-06 09:36 UTC, Yureien commented on Teaching/Blockchain/crypto.md
> +- Best practices for securing Bitcoin wallets, including the importance of backing up private keys and using multi-factor authentication.
Falls under hands-on demonstration.

2023-05-12 14:54 UTC, merged