Create Capture the flag teaching task
kossiitkgp/KOSS-Selection-Tasks pull request #26
Opened 2023-05-03 17:20 UTC by lurkingryuu

This is a task for CTFs and can be modified by adding capture the flag by reverse engineering task.

2023-05-05 17:19 UTC, harshkhandeparkar requested changes
Suggestion: Add a live demonstration hands-on task.

2023-05-05 17:19 UTC, harshkhandeparkar commented on Teaching/Miscellaneous/capture_the_flag.md
> +As part of this task, you will need to create a simple PowerPoint presentation that introduces the concept of Capture the Flag (CTF) competitions to a group of beginners. Your presentation should cov
Please PowerPoint hata do.

2023-05-06 09:33 UTC, Yureien commented on Teaching/Miscellaneous/capture_the_flag.md
> +As part of this task, you will need to create a simple PowerPoint presentation that introduces the concept of Capture the Flag (CTF) competitions to a group of beginners. Your presentation should cov
PPT is fine.

2023-05-06 09:34 UTC, Yureien commented
@lurkingryuu might be better if we ask them to focus on some specific topics (crypto, binexp, web, stegano, etc.) rather than the everything.

2023-05-06 09:37 UTC, lurkingryuu commented
So, I am thinking to concentrate on the topic of reverse engineering, is it fine then?

2023-05-06 09:51 UTC, Yureien commented
> So, I am thinking to concentrate on the topic of reverse engineering, is it fine then? Or we can do 1) Crypto 2) Reverse Engineering.

Sure, works. You can focus on reverse engineering.

2023-05-10 16:59 UTC, merged