Added the WebAssembly task
kossiitkgp/KOSS-Selection-Tasks pull request #34
Opened 2024-01-12 20:32 UTC by Alph3ga

2024-03-14 12:28 UTC, harshkhandeparkar requested changes

2024-03-14 12:28 UTC, harshkhandeparkar commented on Teaching/WebAssembly/webassembly.md
> +WebAssembly is a technology in web development growing in popularity for complex/time-consuming computational taks.
It would be good to explain a bit about what WebAssembly does: Compiled language for the browsers.

2024-03-14 12:28 UTC, harshkhandeparkar commented on Teaching/WebAssembly/webassembly.md
> +- Writing wasm modules in C++
I think giving a rust option is also fine.

2024-03-14 16:28 UTC, Alph3ga commented on Teaching/WebAssembly/webassembly.md
> +Released in 2017, most major browers now support running WebAssembly 1.0 modules in a virtual machine, to be used alongside JavaScript, since by itself it doesn't support features like DOM access.
the DOM access part?

2024-03-14 16:37 UTC, harshkhandeparkar commented on Teaching/WebAssembly/webassembly.md
> +Released in 2017, most major browers now support running WebAssembly 1.0 modules in a virtual machine, to be used alongside JavaScript, since by itself it doesn't support features like DOM access.
Yes, and the 1.0 part.

2024-03-14 17:13 UTC, Alph3ga commented on Teaching/WebAssembly/webassembly.md
> +Released in 2017, most major browers now support running WebAssembly 1.0 modules in a virtual machine, to be used alongside JavaScript, since by itself it doesn't support features like DOM access.
Yes, as per [the official page](https://webassembly.org/features/). Afaik it is supported in most browsers other than outdated stuff like IE or Opera Mini.

2024-03-15 08:55 UTC, harshkhandeparkar approved these changes

2024-03-15 20:04 UTC, merged